name: sws
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9

  # Core Deep Learning
  - tensorflow=2.12.0
  - keras=2.12.0

  # Numerical Computing
  - numpy=1.23.5
  - scipy=1.13.0

  # Visualization
  - matplotlib=3.9.0
  - seaborn=0.13.0
  - imageio=2.37.0

  # Jupyter Environment
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipython=8.12.0
  - ipykernel=6.22.0

  # Additional useful tools
  - h5py  # For Keras model saving/loading
  - pillow  # Image processing
  - pandas  # Data manipulation (seaborn dependency)